//
// This file was auto generated by Visual Studio.
// Menu -> Insert content -> XML in clipboard and this class was generated.
//
namespace vl.Sysmon.Convert.Domain
{
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Sysmon
    {

        private string hashAlgorithmsField;

        private object checkRevocationField;

        private SysmonEventFiltering eventFilteringField;

        private decimal schemaversionField;

        /// <remarks/>
        public string HashAlgorithms
        {
            get
            {
                return this.hashAlgorithmsField;
            }
            set
            {
                this.hashAlgorithmsField = value;
            }
        }

        /// <remarks/>
        public object CheckRevocation
        {
            get
            {
                return this.checkRevocationField;
            }
            set
            {
                this.checkRevocationField = value;
            }
        }

        /// <remarks/>
        public SysmonEventFiltering EventFiltering
        {
            get
            {
                return this.eventFilteringField;
            }
            set
            {
                this.eventFilteringField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal schemaversion
        {
            get
            {
                return this.schemaversionField;
            }
            set
            {
                this.schemaversionField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SysmonEventFiltering
    {

        private object[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FileCreateStreamHash", typeof(SysmonEventFilteringFileCreateStreamHash))]
        [System.Xml.Serialization.XmlElementAttribute("RuleGroup", typeof(SysmonEventFilteringRuleGroup))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SysmonEventFilteringFileCreateStreamHash
    {

        private SysmonEventFilteringFileCreateStreamHashTargetFilename[] targetFilenameField;

        private string onmatchField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TargetFilename")]
        public SysmonEventFilteringFileCreateStreamHashTargetFilename[] TargetFilename
        {
            get
            {
                return this.targetFilenameField;
            }
            set
            {
                this.targetFilenameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string onmatch
        {
            get
            {
                return this.onmatchField;
            }
            set
            {
                this.onmatchField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SysmonEventFilteringFileCreateStreamHashTargetFilename
    {

        private string conditionField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string condition
        {
            get
            {
                return this.conditionField;
            }
            set
            {
                this.conditionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SysmonEventFilteringRuleGroup
    {

        private SysmonEventFilteringRuleGroupDnsQuery dnsQueryField;

        private SysmonEventFilteringRuleGroupWmiEvent wmiEventField;

        private SysmonEventFilteringRuleGroupPipeEvent pipeEventField;

        private SysmonEventFilteringRuleGroupFileCreateStreamHash fileCreateStreamHashField;

        private SysmonEventFilteringRuleGroupRegistryEvent registryEventField;

        private SysmonEventFilteringRuleGroupFileCreate fileCreateField;

        private SysmonEventFilteringRuleGroupProcessAccess processAccessField;

        private SysmonEventFilteringRuleGroupRawAccessRead rawAccessReadField;

        private SysmonEventFilteringRuleGroupCreateRemoteThread createRemoteThreadField;

        private SysmonEventFilteringRuleGroupImageLoad imageLoadField;

        private SysmonEventFilteringRuleGroupDriverLoad driverLoadField;

        private SysmonEventFilteringRuleGroupProcessTerminate processTerminateField;

        private SysmonEventFilteringRuleGroupNetworkConnect networkConnectField;

        private SysmonEventFilteringRuleGroupFileCreateTime fileCreateTimeField;

        private SysmonEventFilteringRuleGroupProcessCreate processCreateField;

        private string nameField;

        private string groupRelationField;

        /// <remarks/>
        public SysmonEventFilteringRuleGroupDnsQuery DnsQuery
        {
            get
            {
                return this.dnsQueryField;
            }
            set
            {
                this.dnsQueryField = value;
            }
        }

        /// <remarks/>
        public SysmonEventFilteringRuleGroupWmiEvent WmiEvent
        {
            get
            {
                return this.wmiEventField;
            }
            set
            {
                this.wmiEventField = value;
            }
        }

        /// <remarks/>
        public SysmonEventFilteringRuleGroupPipeEvent PipeEvent
        {
            get
            {
                return this.pipeEventField;
            }
            set
            {
                this.pipeEventField = value;
            }
        }

        /// <remarks/>
        public SysmonEventFilteringRuleGroupFileCreateStreamHash FileCreateStreamHash
        {
            get
            {
                return this.fileCreateStreamHashField;
            }
            set
            {
                this.fileCreateStreamHashField = value;
            }
        }

        /// <remarks/>
        public SysmonEventFilteringRuleGroupRegistryEvent RegistryEvent
        {
            get
            {
                return this.registryEventField;
            }
            set
            {
                this.registryEventField = value;
            }
        }

        /// <remarks/>
        public SysmonEventFilteringRuleGroupFileCreate FileCreate
        {
            get
            {
                return this.fileCreateField;
            }
            set
            {
                this.fileCreateField = value;
            }
        }

        /// <remarks/>
        public SysmonEventFilteringRuleGroupProcessAccess ProcessAccess
        {
            get
            {
                return this.processAccessField;
            }
            set
            {
                this.processAccessField = value;
            }
        }

        /// <remarks/>
        public SysmonEventFilteringRuleGroupRawAccessRead RawAccessRead
        {
            get
            {
                return this.rawAccessReadField;
            }
            set
            {
                this.rawAccessReadField = value;
            }
        }

        /// <remarks/>
        public SysmonEventFilteringRuleGroupCreateRemoteThread CreateRemoteThread
        {
            get
            {
                return this.createRemoteThreadField;
            }
            set
            {
                this.createRemoteThreadField = value;
            }
        }

        /// <remarks/>
        public SysmonEventFilteringRuleGroupImageLoad ImageLoad
        {
            get
            {
                return this.imageLoadField;
            }
            set
            {
                this.imageLoadField = value;
            }
        }

        /// <remarks/>
        public SysmonEventFilteringRuleGroupDriverLoad DriverLoad
        {
            get
            {
                return this.driverLoadField;
            }
            set
            {
                this.driverLoadField = value;
            }
        }

        /// <remarks/>
        public SysmonEventFilteringRuleGroupProcessTerminate ProcessTerminate
        {
            get
            {
                return this.processTerminateField;
            }
            set
            {
                this.processTerminateField = value;
            }
        }

        /// <remarks/>
        public SysmonEventFilteringRuleGroupNetworkConnect NetworkConnect
        {
            get
            {
                return this.networkConnectField;
            }
            set
            {
                this.networkConnectField = value;
            }
        }

        /// <remarks/>
        public SysmonEventFilteringRuleGroupFileCreateTime FileCreateTime
        {
            get
            {
                return this.fileCreateTimeField;
            }
            set
            {
                this.fileCreateTimeField = value;
            }
        }

        /// <remarks/>
        public SysmonEventFilteringRuleGroupProcessCreate ProcessCreate
        {
            get
            {
                return this.processCreateField;
            }
            set
            {
                this.processCreateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string groupRelation
        {
            get
            {
                return this.groupRelationField;
            }
            set
            {
                this.groupRelationField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SysmonEventFilteringRuleGroupDnsQuery
    {

        private object[] itemsField;

        private string onmatchField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Image", typeof(SysmonEventFilteringRuleGroupDnsQueryImage))]
        [System.Xml.Serialization.XmlElementAttribute("QueryName", typeof(SysmonEventFilteringRuleGroupDnsQueryQueryName))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string onmatch
        {
            get
            {
                return this.onmatchField;
            }
            set
            {
                this.onmatchField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SysmonEventFilteringRuleGroupDnsQueryImage
    {

        private string conditionField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string condition
        {
            get
            {
                return this.conditionField;
            }
            set
            {
                this.conditionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SysmonEventFilteringRuleGroupDnsQueryQueryName
    {

        private string conditionField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string condition
        {
            get
            {
                return this.conditionField;
            }
            set
            {
                this.conditionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SysmonEventFilteringRuleGroupWmiEvent
    {

        private string onmatchField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string onmatch
        {
            get
            {
                return this.onmatchField;
            }
            set
            {
                this.onmatchField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SysmonEventFilteringRuleGroupPipeEvent
    {

        private string onmatchField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string onmatch
        {
            get
            {
                return this.onmatchField;
            }
            set
            {
                this.onmatchField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SysmonEventFilteringRuleGroupFileCreateStreamHash
    {

        private string onmatchField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string onmatch
        {
            get
            {
                return this.onmatchField;
            }
            set
            {
                this.onmatchField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SysmonEventFilteringRuleGroupRegistryEvent
    {

        private object[] itemsField;

        private string onmatchField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EventType", typeof(SysmonEventFilteringRuleGroupRegistryEventEventType))]
        [System.Xml.Serialization.XmlElementAttribute("Image", typeof(SysmonEventFilteringRuleGroupRegistryEventImage))]
        [System.Xml.Serialization.XmlElementAttribute("TargetObject", typeof(SysmonEventFilteringRuleGroupRegistryEventTargetObject))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string onmatch
        {
            get
            {
                return this.onmatchField;
            }
            set
            {
                this.onmatchField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SysmonEventFilteringRuleGroupRegistryEventEventType
    {

        private string conditionField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string condition
        {
            get
            {
                return this.conditionField;
            }
            set
            {
                this.conditionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SysmonEventFilteringRuleGroupRegistryEventImage
    {

        private string nameField;

        private string conditionField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string condition
        {
            get
            {
                return this.conditionField;
            }
            set
            {
                this.conditionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SysmonEventFilteringRuleGroupRegistryEventTargetObject
    {

        private string nameField;

        private string conditionField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string condition
        {
            get
            {
                return this.conditionField;
            }
            set
            {
                this.conditionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SysmonEventFilteringRuleGroupFileCreate
    {

        private object[] itemsField;

        private string onmatchField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Image", typeof(SysmonEventFilteringRuleGroupFileCreateImage))]
        [System.Xml.Serialization.XmlElementAttribute("TargetFilename", typeof(SysmonEventFilteringRuleGroupFileCreateTargetFilename))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string onmatch
        {
            get
            {
                return this.onmatchField;
            }
            set
            {
                this.onmatchField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SysmonEventFilteringRuleGroupFileCreateImage
    {

        private string conditionField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string condition
        {
            get
            {
                return this.conditionField;
            }
            set
            {
                this.conditionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SysmonEventFilteringRuleGroupFileCreateTargetFilename
    {

        private string nameField;

        private string conditionField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string condition
        {
            get
            {
                return this.conditionField;
            }
            set
            {
                this.conditionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SysmonEventFilteringRuleGroupProcessAccess
    {

        private string onmatchField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string onmatch
        {
            get
            {
                return this.onmatchField;
            }
            set
            {
                this.onmatchField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SysmonEventFilteringRuleGroupRawAccessRead
    {

        private string onmatchField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string onmatch
        {
            get
            {
                return this.onmatchField;
            }
            set
            {
                this.onmatchField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SysmonEventFilteringRuleGroupCreateRemoteThread
    {

        private SysmonEventFilteringRuleGroupCreateRemoteThreadSourceImage[] sourceImageField;

        private SysmonEventFilteringRuleGroupCreateRemoteThreadStartModule startModuleField;

        private SysmonEventFilteringRuleGroupCreateRemoteThreadTargetImage targetImageField;

        private string onmatchField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SourceImage")]
        public SysmonEventFilteringRuleGroupCreateRemoteThreadSourceImage[] SourceImage
        {
            get
            {
                return this.sourceImageField;
            }
            set
            {
                this.sourceImageField = value;
            }
        }

        /// <remarks/>
        public SysmonEventFilteringRuleGroupCreateRemoteThreadStartModule StartModule
        {
            get
            {
                return this.startModuleField;
            }
            set
            {
                this.startModuleField = value;
            }
        }

        /// <remarks/>
        public SysmonEventFilteringRuleGroupCreateRemoteThreadTargetImage TargetImage
        {
            get
            {
                return this.targetImageField;
            }
            set
            {
                this.targetImageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string onmatch
        {
            get
            {
                return this.onmatchField;
            }
            set
            {
                this.onmatchField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SysmonEventFilteringRuleGroupCreateRemoteThreadSourceImage
    {

        private string conditionField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string condition
        {
            get
            {
                return this.conditionField;
            }
            set
            {
                this.conditionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SysmonEventFilteringRuleGroupCreateRemoteThreadStartModule
    {

        private string conditionField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string condition
        {
            get
            {
                return this.conditionField;
            }
            set
            {
                this.conditionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SysmonEventFilteringRuleGroupCreateRemoteThreadTargetImage
    {

        private string conditionField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string condition
        {
            get
            {
                return this.conditionField;
            }
            set
            {
                this.conditionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SysmonEventFilteringRuleGroupImageLoad
    {

        private string onmatchField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string onmatch
        {
            get
            {
                return this.onmatchField;
            }
            set
            {
                this.onmatchField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SysmonEventFilteringRuleGroupDriverLoad
    {

        private SysmonEventFilteringRuleGroupDriverLoadSignature[] signatureField;

        private string onmatchField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Signature")]
        public SysmonEventFilteringRuleGroupDriverLoadSignature[] Signature
        {
            get
            {
                return this.signatureField;
            }
            set
            {
                this.signatureField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string onmatch
        {
            get
            {
                return this.onmatchField;
            }
            set
            {
                this.onmatchField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SysmonEventFilteringRuleGroupDriverLoadSignature
    {

        private string conditionField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string condition
        {
            get
            {
                return this.conditionField;
            }
            set
            {
                this.conditionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SysmonEventFilteringRuleGroupProcessTerminate
    {

        private SysmonEventFilteringRuleGroupProcessTerminateImage[] imageField;

        private string onmatchField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Image")]
        public SysmonEventFilteringRuleGroupProcessTerminateImage[] Image
        {
            get
            {
                return this.imageField;
            }
            set
            {
                this.imageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string onmatch
        {
            get
            {
                return this.onmatchField;
            }
            set
            {
                this.onmatchField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SysmonEventFilteringRuleGroupProcessTerminateImage
    {

        private string conditionField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string condition
        {
            get
            {
                return this.conditionField;
            }
            set
            {
                this.conditionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SysmonEventFilteringRuleGroupNetworkConnect
    {

        private SysmonEventFilteringRuleGroupNetworkConnectImage[] imageField;

        private SysmonEventFilteringRuleGroupNetworkConnectDestinationHostname[] destinationHostnameField;

        private SysmonEventFilteringRuleGroupNetworkConnectDestinationIp[] destinationIpField;

        private SysmonEventFilteringRuleGroupNetworkConnectDestinationPort[] destinationPortField;

        private string onmatchField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Image")]
        public SysmonEventFilteringRuleGroupNetworkConnectImage[] Image
        {
            get
            {
                return this.imageField;
            }
            set
            {
                this.imageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DestinationHostname")]
        public SysmonEventFilteringRuleGroupNetworkConnectDestinationHostname[] DestinationHostname
        {
            get
            {
                return this.destinationHostnameField;
            }
            set
            {
                this.destinationHostnameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DestinationIp")]
        public SysmonEventFilteringRuleGroupNetworkConnectDestinationIp[] DestinationIp
        {
            get
            {
                return this.destinationIpField;
            }
            set
            {
                this.destinationIpField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DestinationPort")]
        public SysmonEventFilteringRuleGroupNetworkConnectDestinationPort[] DestinationPort
        {
            get
            {
                return this.destinationPortField;
            }
            set
            {
                this.destinationPortField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string onmatch
        {
            get
            {
                return this.onmatchField;
            }
            set
            {
                this.onmatchField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SysmonEventFilteringRuleGroupNetworkConnectImage
    {

        private string nameField;

        private string conditionField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string condition
        {
            get
            {
                return this.conditionField;
            }
            set
            {
                this.conditionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SysmonEventFilteringRuleGroupNetworkConnectDestinationHostname
    {

        private string conditionField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string condition
        {
            get
            {
                return this.conditionField;
            }
            set
            {
                this.conditionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SysmonEventFilteringRuleGroupNetworkConnectDestinationIp
    {

        private string conditionField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string condition
        {
            get
            {
                return this.conditionField;
            }
            set
            {
                this.conditionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SysmonEventFilteringRuleGroupNetworkConnectDestinationPort
    {

        private string nameField;

        private string conditionField;

        private ushort valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string condition
        {
            get
            {
                return this.conditionField;
            }
            set
            {
                this.conditionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public ushort Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SysmonEventFilteringRuleGroupFileCreateTime
    {

        private object[] itemsField;

        private string onmatchField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Image", typeof(SysmonEventFilteringRuleGroupFileCreateTimeImage))]
        [System.Xml.Serialization.XmlElementAttribute("TargetFilename", typeof(SysmonEventFilteringRuleGroupFileCreateTimeTargetFilename))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string onmatch
        {
            get
            {
                return this.onmatchField;
            }
            set
            {
                this.onmatchField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SysmonEventFilteringRuleGroupFileCreateTimeImage
    {

        private string nameField;

        private string conditionField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string condition
        {
            get
            {
                return this.conditionField;
            }
            set
            {
                this.conditionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SysmonEventFilteringRuleGroupFileCreateTimeTargetFilename
    {

        private string nameField;

        private string conditionField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string condition
        {
            get
            {
                return this.conditionField;
            }
            set
            {
                this.conditionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SysmonEventFilteringRuleGroupProcessCreate
    {

        private object[] itemsField;

        private string onmatchField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CommandLine", typeof(SysmonEventFilteringRuleGroupProcessCreateCommandLine))]
        [System.Xml.Serialization.XmlElementAttribute("Image", typeof(SysmonEventFilteringRuleGroupProcessCreateImage))]
        [System.Xml.Serialization.XmlElementAttribute("IntegrityLevel", typeof(SysmonEventFilteringRuleGroupProcessCreateIntegrityLevel))]
        [System.Xml.Serialization.XmlElementAttribute("ParentCommandLine", typeof(SysmonEventFilteringRuleGroupProcessCreateParentCommandLine))]
        [System.Xml.Serialization.XmlElementAttribute("ParentImage", typeof(SysmonEventFilteringRuleGroupProcessCreateParentImage))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string onmatch
        {
            get
            {
                return this.onmatchField;
            }
            set
            {
                this.onmatchField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SysmonEventFilteringRuleGroupProcessCreateCommandLine
    {

        private string conditionField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string condition
        {
            get
            {
                return this.conditionField;
            }
            set
            {
                this.conditionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SysmonEventFilteringRuleGroupProcessCreateImage
    {

        private string conditionField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string condition
        {
            get
            {
                return this.conditionField;
            }
            set
            {
                this.conditionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SysmonEventFilteringRuleGroupProcessCreateIntegrityLevel
    {

        private string conditionField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string condition
        {
            get
            {
                return this.conditionField;
            }
            set
            {
                this.conditionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SysmonEventFilteringRuleGroupProcessCreateParentCommandLine
    {

        private string conditionField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string condition
        {
            get
            {
                return this.conditionField;
            }
            set
            {
                this.conditionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SysmonEventFilteringRuleGroupProcessCreateParentImage
    {

        private string conditionField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string condition
        {
            get
            {
                return this.conditionField;
            }
            set
            {
                this.conditionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }


}